# Домашнее задание. Урок 22. Библиотека NumPy

В работе используются только средства, разобранные на занятии: создание массивов,
атрибуты `shape` / `dtype` / `size`, поэлементные операции, булева индексация
и агрегирующие методы с параметром `axis`.

In [1]:
import numpy as np

print("Версия NumPy:", np.__version__)

# Генератор случайных чисел с фиксированным зерном.
# Зерно нужно, чтобы при повторном запуске блокнота получались те же числа,
# и выводы в тексте не расходились с результатами.
rng = np.random.default_rng(2026)

Версия NumPy: 2.4.6


## Задание 1

Создать одномерный массив из 15 случайных целых чисел от 1 до 100,
вывести его форму, тип данных и количество элементов.

In [2]:
values = rng.integers(1, 101, size=15)

print("Массив:", values)
print()
print("Форма      (shape):", values.shape)
print("Тип данных (dtype):", values.dtype)
print("Количество (size) :", values.size)

Массив: [86 18  3 64 37 47  8 38 65 36 84 80 71 91 73]

Форма      (shape): (15,)
Тип данных (dtype): int64
Количество (size) : 15


Верхняя граница в `integers` не включается, поэтому для диапазона 1...100
указан `101`.

Форма выводится как кортеж с одним числом — `(15,)`. Запятая здесь не опечатка:
именно она отличает кортеж из одного элемента от обычного числа в скобках.
Один элемент в кортеже означает, что массив одномерный.

## Задание 2

Отобрать булевой индексацией все значения больше 50, посчитать их количество
и долю от общего числа элементов.

In [3]:
mask = values > 50        # массив из True/False той же длины, что и values
large = values[mask]      # остаются только элементы, напротив которых True

share = large.size / values.size

print("Маска:          ", mask)
print("Значения > 50:  ", large)
print()
print("Сколько таких значений:", large.size)
print("Доля от всех элементов:", share)
print("Та же доля в процентах: {:.1f}%".format(share * 100))

Маска:           [ True False False  True False False False False  True False  True  True
  True  True  True]
Значения > 50:   [86 64 65 84 80 71 91 73]

Сколько таких значений: 8
Доля от всех элементов: 0.5333333333333333
Та же доля в процентах: 53.3%


Сравнение `values > 50` применяется сразу ко всему массиву и возвращает не одно
значение `True` или `False`, а целый массив из них. Когда такой булев массив
используется как индекс, NumPy оставляет только те позиции, где стоит `True`.

Количество отобранных значений удобно взять как `large.size` — отдельно считать
ничего не нужно, потому что длина получившегося массива и есть искомое число.

## Задание 3

Создать массив из 10 значений времени ответа оператора поддержки в секундах,
перевести его в минуты одной строкой без цикла, вычислить среднее,
минимальное и максимальное значение.

In [4]:
response_sec = rng.integers(15, 301, size=10)

# Перевод в минуты. Деление применяется сразу ко всем элементам массива,
# поэтому цикл не нужен — это и есть векторизованная операция.
response_min = response_sec / 60

print("Время ответа, секунды:", response_sec)
print("Время ответа, минуты :", response_min)
print()
print("Среднее время, мин     :", response_min.mean())
print("Минимальное время, мин :", response_min.min())
print("Максимальное время, мин:", response_min.max())

Время ответа, секунды: [ 65 260 201  43 100  62 291 223 278  95]
Время ответа, минуты : [1.08333333 4.33333333 3.35       0.71666667 1.66666667 1.03333333
 4.85       3.71666667 4.63333333 1.58333333]

Среднее время, мин     : 2.6966666666666663
Минимальное время, мин : 0.7166666666666667
Максимальное время, мин: 4.85


Диапазон взят от 15 до 300 секунд — это правдоподобное время ответа оператора
первой линии: от 15 секунд до пяти минут.

Обратите внимание на тип данных: массив секунд целочисленный, а после деления
на 60 получается массив вещественных чисел. NumPy меняет тип автоматически,
чтобы не терять дробную часть.

In [5]:
# Проверка типов до и после деления
print("dtype секунд:", response_sec.dtype)
print("dtype минут :", response_min.dtype)

dtype секунд: int64
dtype минут : float64


## Задание 4

Создать матрицу 4x3 — 4 студента и 3 оценки по предметам, целые числа от 1 до 5.
Посчитать среднюю оценку по каждому студенту и по каждому предмету.

В формулировке задания сказано «средняя оценка по каждому клиенту», но по смыслу
речь идёт о студентах, поэтому далее используется слово «студент».

In [6]:
marks = rng.integers(1, 6, size=(4, 3))

print("Матрица оценок, строки — студенты, столбцы — предметы:")
print(marks)

Матрица оценок, строки — студенты, столбцы — предметы:
[[4 4 4]
 [1 3 4]
 [5 4 3]
 [3 2 1]]


In [7]:
# axis=1 — сворачиваем строку, то есть усредняем три предмета одного студента
by_student = marks.mean(axis=1)

# axis=0 — сворачиваем столбец, то есть усредняем всех студентов по одному предмету
by_subject = marks.mean(axis=0)

print("Средняя оценка каждого студента:", by_student)
print("Средняя оценка по предметам    :", by_subject)

Средняя оценка каждого студента: [4.         2.66666667 4.         2.        ]
Средняя оценка по предметам    : [3.25 3.25 3.  ]


Параметр `axis` — самое частое место ошибок, поэтому стоит проговорить его смысл.
`axis` указывает не на то, *что* мы усредняем, а на то, какая ось **исчезает**
в результате.

Матрица имеет форму `(4, 3)`: ось 0 — студенты, ось 1 — предметы.

- `axis=1` убирает ось предметов, остаётся 4 числа — по одному на студента;
- `axis=0` убирает ось студентов, остаётся 3 числа — по одному на предмет.

Проще всего проверить себя по длине результата.

In [8]:
print("Форма исходной матрицы :", marks.shape)
print("Результат по студентам :", by_student.shape, "— 4 значения, по числу студентов")
print("Результат по предметам :", by_subject.shape, "— 3 значения, по числу предметов")
print()
print("Средняя оценка по всей матрице:", marks.mean())

Форма исходной матрицы : (4, 3)
Результат по студентам : (4,) — 4 значения, по числу студентов
Результат по предметам : (3,) — 3 значения, по числу предметов

Средняя оценка по всей матрице: 3.1666666666666665


## Вывод

В работе использованы четыре базовых механизма NumPy:

1. создание массивов заданной формы генератором `default_rng`;
2. атрибуты массива `shape`, `dtype`, `size`, описывающие его структуру;
3. булева индексация, позволяющая отбирать элементы по условию без цикла;
4. агрегирующие методы с параметром `axis` для подсчёта по строкам и столбцам.

Общее у всех четырёх заданий одно: ни в одном из них не понадобился цикл `for`.
Операция записывается сразу для всего массива, и за счёт этого код получается
короче и работает быстрее, чем поэлементная обработка списков.